blank_issues_enabled: false
contact_links:
    about: Please ask and answer questions here
  - name: Slack Workspace
    url: https://hospitalrun-slack.herokuapp.com/
    about: Please ask and answer questions here
